# Call Analysis Configuration
scoring:
  # Fuzzy matching threshold (0-100)
  fuzzy_threshold: 80
  # Semantic similarity threshold (0-1)
  semantic_threshold: 0.7
  # Minimum confidence for keyword detection
  keyword_confidence_threshold: 0.6

# Agent behavior phrases for rule-based scoring
agent_behaviour_phrases:
  Customer Understanding:
    - "do you understand"
    - "let me explain"
    - "does that make sense"
    - "is that clear"
    - "just to clarify"
    - "i'll walk you through"
    - "happy to explain again"
    - "take your time to understand"
    - "feel free to ask questions"
    - "would you like me to repeat"
    - "explain it simply"
    - "easy to understand"
    - "clear explanation"
    - "any questions so far"
    - "let me break that down"
    - "i can rephrase that for you"
    - "can you explain that again"
    - "i'm confused"
    - "I don't understand"
    - "I have memory problems"
    - "learning difficulties"
    - "someone helps me"
    - "I'm not sure what you mean"
    - "this is all very confusing"
    - "I need someone to help me understand"
    
  Fair Treatment:
    - "we're here to help"
    - "take your time"
    - "you have options"
    - "we won't pressure you"
    - "we want what's best for you"
    - "we'll support you"
    - "no obligation"
    - "your decision"
    - "you're in control"
    - "we'll do our best"
    - "treat you fairly"
    - "understand your situation"
    - "i understand this is a challenging time for you"
    - "I can see how difficult this must be"
    - "I appreciate you sharing this with me"
    - "That sounds really tough"
    - "I want to make sure I understand correctly"
    
  Vulnerability Handling:
    - "can I ask if you're okay"
    - "do you need any support"
    - "we support mental health"
    - "are you getting help"
    - "do you have a medical condition"
    - "we can pause the account"
    - "we can send a breathing space form"
    - "you don't have to explain"
    - "we understand vulnerability"
    - "difficult situation"
    - "i understand this is a challenging time for you"
    - "what is happening on your side"
    - "difficult situation"
    - "what is happening on your side"
    
  Financial Difficulty:
    - "we can set up a plan"
    - "we can work something out"
    - "affordable repayment"
    - "can pause payments"
    - "need income and expenditure"
    - "repayment flexibility"
    - "let's look at options"
    - "freeze interest"
    - "we'll be fair"
     - "a lot to pay for"
    - "waiting on redundancy payment"
    - "we'll review your income & expenditure"
    
  Resolution & Support:
    - "we'll investigate"
    - "we'll raise a complaint"
    - "we can escalate this"
    - "here's what we'll do"
    - "next steps"
    - "i've raised that for you"
    - "we'll send confirmation"
    - "thank you for confirming"
    - "anything else I can help you with"

# NLP concepts for semantic analysis
nlp_concepts:
  Customer Understanding:
    - "explanation"
    - "clarification"
    - "understanding"
    - "comprehension"
    - "guidance"
    - "instruction"
    - "confusion"
    - "memory issues"
    - "learning support"
    - "cognitive difficulty"
    - "comprehension issue"
    
  Fair Treatment:
    - "fairness"
    - "respect"
    - "dignity"
    - "equality"
    - "justice"
    - "consideration"
    - "empathy"
    - "acknowledgment"
    - "recognition"
    - "validation"
    - "compassion"
    
  Vulnerability Handling:
    - "vulnerability"
    - "support"
    - "assistance"
    - "care"
    - "protection"
    - "wellbeing"
    - "mental health"
    - "disability"
    - "accommodation"
    - "cognitive impairment"
    - "learning barrier"
    
  Financial Difficulty:
    - "affordability"
    - "flexibility"
    - "arrangement"
    - "solution"
    - "plan"
    - "option"
    - "hardship"
    - "benefit dependency"
    - "unemployment"
    - "income assessment"
    
  Resolution & Support:
    - "resolution"
    - "solution"
    - "escalation"
    - "investigation"
    - "action"
    - "follow-up"
    - "confirmation"
    - "assistance"
    - "support completion"
    

# Keywords for detection with confidence scoring
keywords:
  high_priority:
    - "vulnerable"
    - "complaint"
    - "suicide"
    - "harassment"
    - "threaten"
    - "scam"
    - "police"
    - "terminal"
    - "cancer"
    - "sectioned"
    - "domestic violence"
    - "psychosis"
    - "abused"
    - "abusive"
    - "coercion"
    - "lacks understanding"
    - "manipulated"
    - "mental breakdown"
    - "restraining order"
    - "refuge"
    - "feel like giving up"
    - "breaking point"
    - "i've had enough"
    
  medium_priority:
    - "mental health"
    - "depression"
    - "anxiety"
    - "stress"
    - "struggling"
    - "financial difficulties"
    - "unable to pay"
    - "late payment"
    - "refund"
    - "collection"
    - "signed off"
    - "injury"
    - "breathing space"
    - "death"
    - "diagnosis"
    - "bipolar"
    - "PTSD"
    - "ADHD"
    - "autism"
    - "disabilities"
    - "long term sick"
    - "therapist"
    - "rehabilitation"
    - "homeless"
    - "sofa surfing"
    - "disorientated"
    - "sicknote"
    - "medication"
    - "job loss"
    - "bailiffs"
    - "CCJ"
    - "eviction"
    - "foodbank"
    - "divorce"
    - "antidepressants"
    - "chronic pain"
    - "mobility issues"
    - "funeral"
    - "debt management"
    - "step change"
    - "overdrawn"
    - "no money"
    - "no income"
    - "rent arrears"
    - "overcommitted"
    - "grieving"
    - "child unwell"
    - "temporary accommodation"
    
  low_priority:
    - "manager"
    - "write off"
    - "bereavement"
    - "deaf"
    - "blind"
    - "disabled"
    - "unemployed"
    - "homeless"
    - "illness"
    - "surgery"
    - "feeling low"
    - "stressed"
    - "side effects"
    - "grieving"
    - "drug"
    - "addiction"
    - "alcohol"
    - "repossession"
    - "arrears"
    - "forbearance"
    - "tax credit"
    - "universal credit"
    - "benefits"
    - "PIP"
    - "personal independent pay"
    - "sickpay"

# Audio processing settings
audio:
  supported_formats:
    - "mp3"
    - "wav"
    - "m4a"
    - "flac"
    - "aac"
    - "ogg"
  max_file_size_mb: 100
  chunk_duration_minutes: 10
  normalize_audio: true
  noise_reduction: true

# Security settings
security:
  redact_pii: true
  secure_temp_files: true
  auto_cleanup: true
  encryption_key_file: "encryption.key"
  
# PII patterns for redaction
pii_patterns:
  phone_numbers:
    - pattern: '\b(?:\+44\s?)?(?:\(?0\d{4}\)?\s?\d{6}|\(?0\d{3}\)?\s?\d{7})\b'
      replacement: "[PHONE]"
  emails:
    - pattern: '\b[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Z|a-z]{2,}\b'
      replacement: "[EMAIL]"
  postcodes:
    - pattern: '\b[A-Z]{1,2}\d[A-Z\d]?\s?\d[A-Z]{2}\b'
      replacement: "[POSTCODE]"
  account_numbers:
    - pattern: '\b(?:account|acc|ref)(?:\s*(?:number|no|#))?\s*:?\s*\d{6,12}\b'
      replacement: "[ACCOUNT]"
  sort_codes:
    - pattern: '\b\d{2}-\d{2}-\d{2}\b'
      replacement: "[SORTCODE]"
