import json
import os
from datetime import date, datetime
from typing import Any, Dict, List

import pandas as pd
import psycopg2


class PostgresCallAnalysisDB:
    def __init__(self, database_url: str, schema: str = "call_analysis"):
        self.database_url = database_url
        self.schema = schema
        self.init_database()

    def _connect(self):
        return psycopg2.connect(self.database_url)

    def _q(self, table_name: str) -> str:
        return f'"{self.schema}"."{table_name}"'

    def init_database(self):
        with self._connect() as conn:
            cursor = conn.cursor()
            cursor.execute(f'CREATE SCHEMA IF NOT EXISTS "{self.schema}"')
            cursor.execute(f"CREATE TABLE IF NOT EXISTS {self._q('agents')} (agent_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, agent_name TEXT UNIQUE NOT NULL, department TEXT, start_date DATE, is_active BOOLEAN DEFAULT TRUE, created_at TIMESTAMPTZ DEFAULT NOW())")
            cursor.execute(f"CREATE TABLE IF NOT EXISTS {self._q('calls')} (call_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, agent_id BIGINT REFERENCES {self._q('agents')}(agent_id), filename TEXT NOT NULL, call_date DATE NOT NULL, call_type TEXT, duration_minutes DOUBLE PRECISION, transcript TEXT, sentiment TEXT, customer_sentiment TEXT, customer_text_sample TEXT, customer_sentiment_confidence DOUBLE PRECISION, processing_time_seconds DOUBLE PRECISION, file_size_mb DOUBLE PRECISION, created_at TIMESTAMPTZ DEFAULT NOW())")
            cursor.execute(f"CREATE TABLE IF NOT EXISTS {self._q('keywords')} (keyword_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, call_id BIGINT REFERENCES {self._q('calls')}(call_id) ON DELETE CASCADE, keyword_phrase TEXT NOT NULL, confidence DOUBLE PRECISION, priority TEXT, match_type TEXT)")
            cursor.execute(f"CREATE TABLE IF NOT EXISTS {self._q('qa_scores')} (score_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, call_id BIGINT REFERENCES {self._q('calls')}(call_id) ON DELETE CASCADE, scoring_method TEXT, category TEXT NOT NULL, score DOUBLE PRECISION NOT NULL, confidence DOUBLE PRECISION, explanation TEXT, matched_phrase TEXT, holistic_score DOUBLE PRECISION, frequency DOUBLE PRECISION, frequency_score DOUBLE PRECISION, semantic_quality DOUBLE PRECISION, distribution DOUBLE PRECISION, details_json JSONB, text_scope TEXT)")
            cursor.execute(f"CREATE TABLE IF NOT EXISTS {self._q('monthly_summaries')} (summary_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, agent_id BIGINT REFERENCES {self._q('agents')}(agent_id), year INTEGER, month INTEGER, total_calls INTEGER DEFAULT 0, avg_rule_score DOUBLE PRECISION DEFAULT 0, avg_nlp_score DOUBLE PRECISION DEFAULT 0, total_duration_minutes DOUBLE PRECISION DEFAULT 0, positive_sentiment_count INTEGER DEFAULT 0, negative_sentiment_count INTEGER DEFAULT 0, neutral_sentiment_count INTEGER DEFAULT 0, last_updated TIMESTAMPTZ DEFAULT NOW(), UNIQUE(agent_id, year, month))")
            cursor.execute(f"CREATE INDEX IF NOT EXISTS idx_calls_agent_date ON {self._q('calls')} (agent_id, call_date)")
            cursor.execute(f"CREATE INDEX IF NOT EXISTS idx_qa_scores_call ON {self._q('qa_scores')} (call_id)")
            cursor.execute(f"CREATE INDEX IF NOT EXISTS idx_keywords_call ON {self._q('keywords')} (call_id)")
            cursor.execute(f"CREATE INDEX IF NOT EXISTS idx_monthly_summaries_agent ON {self._q('monthly_summaries')} (agent_id, year, month)")
            conn.commit()

    def add_agent(self, agent_name: str, department: str = None) -> int:
        with self._connect() as conn:
            cursor = conn.cursor()
            cursor.execute(f"INSERT INTO {self._q('agents')} (agent_name, department, start_date) VALUES (%s, %s, %s) ON CONFLICT (agent_name) DO UPDATE SET department = COALESCE(EXCLUDED.department, {self._q('agents')}.department) RETURNING agent_id", (agent_name, department, date.today()))
            agent_id = cursor.fetchone()[0]
            conn.commit()
            return agent_id
    def _insert_scores(self, cursor, call_id: int, scoring_method: str, scores: Dict[str, Any]):
        for category, result in scores.items():
            cursor.execute(f"INSERT INTO {self._q('qa_scores')} (call_id, scoring_method, category, score, confidence, explanation, matched_phrase, holistic_score, frequency, frequency_score, semantic_quality, distribution, details_json, text_scope) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s::jsonb, %s)", (call_id, scoring_method, category, result['score'], result.get('confidence', 0), result.get('explanation', ''), result.get('matched_phrase', ''), result.get('holistic_score', result.get('score', 0)), result.get('frequency', 0), result.get('frequency_score'), result.get('semantic_quality'), result.get('distribution'), json.dumps(result.get('details', {})), result.get('text_scope', 'agent_only')))

    def save_call_analysis(self, agent_name: str, call_data: Dict[str, Any]) -> int:
        with self._connect() as conn:
            cursor = conn.cursor()
            agent_id = self.add_agent(agent_name, call_data.get('department'))
            metadata = call_data.get('metadata', {})
            cursor.execute(f"INSERT INTO {self._q('calls')} (agent_id, filename, call_date, call_type, duration_minutes, transcript, sentiment, customer_sentiment, customer_text_sample, customer_sentiment_confidence, processing_time_seconds, file_size_mb) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s) RETURNING call_id", (agent_id, call_data['filename'], call_data.get('call_date', date.today()), call_data.get('call_type', 'Unknown'), metadata.get('duration_minutes', 0), call_data['transcript'], call_data.get('sentiment', 'Unknown'), call_data.get('customer_sentiment', 'unknown'), call_data.get('customer_text_sample', ''), call_data.get('customer_sentiment_confidence', 0), call_data.get('processing_time', 0), metadata.get('file_size_mb', 0)))
            call_id = cursor.fetchone()[0]
            for keyword in call_data.get('keywords_enhanced', []):
                cursor.execute(f"INSERT INTO {self._q('keywords')} (call_id, keyword_phrase, confidence, priority, match_type) VALUES (%s, %s, %s, %s, %s)", (call_id, keyword.get('phrase', ''), keyword.get('confidence', 0), keyword.get('priority', 'medium'), keyword.get('match_type', 'exact')))
            self._insert_scores(cursor, call_id, 'rule_based', call_data.get('qa_results', {}))
            self._insert_scores(cursor, call_id, 'nlp_enhanced', call_data.get('qa_results_nlp', {}))
            conn.commit()
            self.update_monthly_summary(agent_id, call_data.get('call_date', date.today()))
            return call_id

    def update_monthly_summary(self, agent_id: int, call_date: date):
        year, month = call_date.year, call_date.month
        with self._connect() as conn:
            cursor = conn.cursor()
            cursor.execute(f"SELECT COUNT(*), COALESCE(SUM(duration_minutes), 0), SUM(CASE WHEN LOWER(COALESCE(customer_sentiment, sentiment, '')) = 'positive' THEN 1 ELSE 0 END), SUM(CASE WHEN LOWER(COALESCE(customer_sentiment, sentiment, '')) = 'negative' THEN 1 ELSE 0 END), SUM(CASE WHEN LOWER(COALESCE(customer_sentiment, sentiment, '')) = 'neutral' THEN 1 ELSE 0 END) FROM {self._q('calls')} WHERE agent_id = %s AND EXTRACT(YEAR FROM call_date) = %s AND EXTRACT(MONTH FROM call_date) = %s", (agent_id, year, month))
            call_stats = cursor.fetchone()
            cursor.execute(f"SELECT AVG(CASE WHEN qs.scoring_method = 'rule_based' THEN qs.score END), AVG(CASE WHEN qs.scoring_method = 'nlp_enhanced' THEN COALESCE(qs.holistic_score, qs.score) END) FROM {self._q('qa_scores')} qs JOIN {self._q('calls')} c ON qs.call_id = c.call_id WHERE c.agent_id = %s AND EXTRACT(YEAR FROM c.call_date) = %s AND EXTRACT(MONTH FROM c.call_date) = %s", (agent_id, year, month))
            score_stats = cursor.fetchone()
            cursor.execute(f"INSERT INTO {self._q('monthly_summaries')} (agent_id, year, month, total_calls, avg_rule_score, avg_nlp_score, total_duration_minutes, positive_sentiment_count, negative_sentiment_count, neutral_sentiment_count, last_updated) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, NOW()) ON CONFLICT (agent_id, year, month) DO UPDATE SET total_calls = EXCLUDED.total_calls, avg_rule_score = EXCLUDED.avg_rule_score, avg_nlp_score = EXCLUDED.avg_nlp_score, total_duration_minutes = EXCLUDED.total_duration_minutes, positive_sentiment_count = EXCLUDED.positive_sentiment_count, negative_sentiment_count = EXCLUDED.negative_sentiment_count, neutral_sentiment_count = EXCLUDED.neutral_sentiment_count, last_updated = NOW()", (agent_id, year, month, call_stats[0] or 0, score_stats[0] or 0, score_stats[1] or 0, call_stats[1] or 0, call_stats[2] or 0, call_stats[3] or 0, call_stats[4] or 0))
            conn.commit()

    def get_agent_scores_by_month(self, agent_name: str = None, year: int = None) -> pd.DataFrame:
        with self._connect() as conn:
            query = f"SELECT a.agent_name, ms.year, ms.month, ms.total_calls, ROUND(ms.avg_rule_score::numeric, 2) as avg_rule_score, ROUND(ms.avg_nlp_score::numeric, 2) as avg_nlp_score, ROUND(ms.total_duration_minutes::numeric, 1) as total_duration_minutes, ms.positive_sentiment_count, ms.negative_sentiment_count, ms.neutral_sentiment_count FROM {self._q('monthly_summaries')} ms JOIN {self._q('agents')} a ON ms.agent_id = a.agent_id WHERE a.is_active = TRUE"
            params: List[Any] = []
            if agent_name:
                query += " AND a.agent_name = %s"
                params.append(agent_name)
            if year:
                query += " AND ms.year = %s"
                params.append(year)
            query += " ORDER BY a.agent_name, ms.year DESC, ms.month DESC"
            return pd.read_sql_query(query, conn, params=params)
    def get_dashboard_data(self, start_date: date = None, end_date: date = None) -> Dict[str, Any]:
        if not start_date:
            start_date = date.today().replace(month=1, day=1)
        if not end_date:
            end_date = date.today()
        with self._connect() as conn:
            overview_calls = pd.read_sql_query(f"SELECT COUNT(DISTINCT agent_id) as total_agents, COUNT(*) as total_calls, COALESCE(SUM(duration_minutes),0) as total_duration_minutes FROM {self._q('calls')} WHERE call_date BETWEEN %s AND %s", conn, params=[start_date, end_date])
            overview_scores = pd.read_sql_query(f"SELECT AVG(CASE WHEN qs.scoring_method = 'rule_based' THEN qs.score END) as avg_rule_score, AVG(CASE WHEN qs.scoring_method = 'nlp_enhanced' THEN COALESCE(qs.holistic_score, qs.score) END) as avg_nlp_score FROM {self._q('qa_scores')} qs JOIN {self._q('calls')} c ON qs.call_id = c.call_id WHERE c.call_date BETWEEN %s AND %s", conn, params=[start_date, end_date])
            agent_performance = pd.read_sql_query(f"WITH scores_by_call AS (SELECT call_id, AVG(CASE WHEN scoring_method = 'rule_based' THEN score END) as rule_score, AVG(CASE WHEN scoring_method = 'nlp_enhanced' THEN COALESCE(holistic_score, score) END) as nlp_score FROM {self._q('qa_scores')} GROUP BY call_id) SELECT a.agent_name, a.department, COUNT(c.call_id) as total_calls, AVG(sbc.rule_score) as avg_rule_score, AVG(sbc.nlp_score) as avg_nlp_score, COALESCE(SUM(c.duration_minutes),0) as total_duration_minutes, SUM(CASE WHEN LOWER(COALESCE(c.customer_sentiment, c.sentiment, '')) = 'positive' THEN 1 ELSE 0 END) as positive_calls, SUM(CASE WHEN LOWER(COALESCE(c.customer_sentiment, c.sentiment, '')) = 'negative' THEN 1 ELSE 0 END) as negative_calls FROM {self._q('agents')} a LEFT JOIN {self._q('calls')} c ON a.agent_id = c.agent_id AND c.call_date BETWEEN %s AND %s LEFT JOIN scores_by_call sbc ON c.call_id = sbc.call_id WHERE a.is_active = TRUE GROUP BY a.agent_id, a.agent_name, a.department HAVING COUNT(c.call_id) > 0 ORDER BY avg_rule_score DESC", conn, params=[start_date, end_date])
            monthly_trends = pd.read_sql_query(f"WITH scores_by_call AS (SELECT call_id, AVG(CASE WHEN scoring_method = 'rule_based' THEN score END) as rule_score, AVG(CASE WHEN scoring_method = 'nlp_enhanced' THEN COALESCE(holistic_score, score) END) as nlp_score FROM {self._q('qa_scores')} GROUP BY call_id) SELECT TO_CHAR(c.call_date, 'YYYY-MM') as month, COUNT(*) as total_calls, AVG(sbc.rule_score) as avg_rule_score, AVG(sbc.nlp_score) as avg_nlp_score FROM {self._q('calls')} c LEFT JOIN scores_by_call sbc ON c.call_id = sbc.call_id WHERE c.call_date BETWEEN %s AND %s GROUP BY TO_CHAR(c.call_date, 'YYYY-MM') ORDER BY month", conn, params=[start_date, end_date])
            category_breakdown = pd.read_sql_query(f"SELECT qs.category, qs.scoring_method, AVG(CASE WHEN qs.scoring_method = 'nlp_enhanced' THEN COALESCE(qs.holistic_score, qs.score) ELSE qs.score END) as avg_score, COUNT(*) as total_evaluations FROM {self._q('qa_scores')} qs JOIN {self._q('calls')} c ON qs.call_id = c.call_id WHERE c.call_date BETWEEN %s AND %s GROUP BY qs.category, qs.scoring_method ORDER BY qs.category, qs.scoring_method", conn, params=[start_date, end_date])
            return {"overview": {**(overview_calls.to_dict('records')[0] if not overview_calls.empty else {}), **(overview_scores.to_dict('records')[0] if not overview_scores.empty else {})}, "agent_performance": agent_performance, "monthly_trends": monthly_trends, "category_breakdown": category_breakdown}

    def get_all_agents(self) -> List[str]:
        with self._connect() as conn:
            cursor = conn.cursor()
            cursor.execute(f"SELECT agent_name FROM {self._q('agents')} WHERE is_active = TRUE ORDER BY agent_name")
            return [row[0] for row in cursor.fetchall()]

    def delete_call(self, call_id: int):
        with self._connect() as conn:
            cursor = conn.cursor()
            cursor.execute(f"SELECT agent_id, call_date FROM {self._q('calls')} WHERE call_id = %s", (call_id,))
            result = cursor.fetchone()
            if result:
                agent_id, call_date_value = result
                cursor.execute(f"DELETE FROM {self._q('calls')} WHERE call_id = %s", (call_id,))
                conn.commit()
                self.update_monthly_summary(agent_id, call_date_value)
    def reassign_calls_to_agent(self, from_agent_name: str, to_agent_name: str, call_ids: List[int] = None) -> int:
        with self._connect() as conn:
            cursor = conn.cursor()
            cursor.execute(f"SELECT agent_id FROM {self._q('agents')} WHERE agent_name = %s", (from_agent_name,))
            from_result = cursor.fetchone()
            if not from_result:
                raise ValueError(f"Agent '{from_agent_name}' not found in database")
            from_agent_id = from_result[0]
            to_agent_id = self.add_agent(to_agent_name)
            if call_ids:
                placeholders = ",".join(["%s" for _ in call_ids])
                cursor.execute(f"SELECT DISTINCT call_date FROM {self._q('calls')} WHERE agent_id = %s AND call_id IN ({placeholders})", [from_agent_id] + call_ids)
                affected_dates = [row[0] for row in cursor.fetchall()]
                cursor.execute(f"UPDATE {self._q('calls')} SET agent_id = %s WHERE agent_id = %s AND call_id IN ({placeholders})", [to_agent_id, from_agent_id] + call_ids)
            else:
                cursor.execute(f"SELECT DISTINCT call_date FROM {self._q('calls')} WHERE agent_id = %s", (from_agent_id,))
                affected_dates = [row[0] for row in cursor.fetchall()]
                cursor.execute(f"UPDATE {self._q('calls')} SET agent_id = %s WHERE agent_id = %s", (to_agent_id, from_agent_id))
            reassigned_count = cursor.rowcount
            conn.commit()
            for call_date_value in affected_dates:
                self.update_monthly_summary(from_agent_id, call_date_value)
                self.update_monthly_summary(to_agent_id, call_date_value)
            return reassigned_count

    def merge_agents(self, misspelled_name: str, correct_name: str, delete_misspelled: bool = True) -> Dict[str, Any]:
        with self._connect() as conn:
            cursor = conn.cursor()
            cursor.execute(f"SELECT agent_id FROM {self._q('agents')} WHERE agent_name = %s", (misspelled_name,))
            misspelled = cursor.fetchone()
            if not misspelled:
                raise ValueError(f"Agent '{misspelled_name}' not found")
            reassigned = self.reassign_calls_to_agent(misspelled_name, correct_name)
            if delete_misspelled:
                cursor.execute(f"UPDATE {self._q('agents')} SET is_active = FALSE WHERE agent_name = %s", (misspelled_name,))
                conn.commit()
            return {'misspelled_agent': misspelled_name, 'correct_agent': correct_name, 'calls_reassigned': reassigned, 'misspelled_deactivated': delete_misspelled}

    def list_agents_with_call_counts(self) -> List[Dict[str, Any]]:
        with self._connect() as conn:
            cursor = conn.cursor()
            cursor.execute(f"SELECT a.agent_id, a.agent_name, a.is_active, COUNT(c.call_id) as call_count FROM {self._q('agents')} a LEFT JOIN {self._q('calls')} c ON a.agent_id = c.agent_id GROUP BY a.agent_id, a.agent_name, a.is_active ORDER BY a.agent_name")
            return [{'agent_id': row[0], 'agent_name': row[1], 'is_active': bool(row[2]), 'call_count': row[3]} for row in cursor.fetchall()]
