create schema if not exists call_analysis;

create table if not exists call_analysis.agents (
    agent_id bigint generated by default as identity primary key,
    agent_name text unique not null,
    department text,
    start_date date,
    is_active boolean default true,
    created_at timestamptz default now()
);

create table if not exists call_analysis.calls (
    call_id bigint generated by default as identity primary key,
    agent_id bigint references call_analysis.agents(agent_id),
    filename text not null,
    call_date date not null,
    call_type text,
    duration_minutes double precision,
    transcript text,
    sentiment text,
    customer_sentiment text,
    customer_text_sample text,
    customer_sentiment_confidence double precision,
    processing_time_seconds double precision,
    file_size_mb double precision,
    created_at timestamptz default now()
);

create table if not exists call_analysis.keywords (
    keyword_id bigint generated by default as identity primary key,
    call_id bigint references call_analysis.calls(call_id) on delete cascade,
    keyword_phrase text not null,
    confidence double precision,
    priority text,
    match_type text
);

create table if not exists call_analysis.qa_scores (
    score_id bigint generated by default as identity primary key,
    call_id bigint references call_analysis.calls(call_id) on delete cascade,
    scoring_method text,
    category text not null,
    score double precision not null,
    confidence double precision,
    explanation text,
    matched_phrase text,
    holistic_score double precision,
    frequency double precision,
    frequency_score double precision,
    semantic_quality double precision,
    distribution double precision,
    details_json jsonb,
    text_scope text
);

create table if not exists call_analysis.monthly_summaries (
    summary_id bigint generated by default as identity primary key,
    agent_id bigint references call_analysis.agents(agent_id),
    year integer,
    month integer,
    total_calls integer default 0,
    avg_rule_score double precision default 0,
    avg_nlp_score double precision default 0,
    total_duration_minutes double precision default 0,
    positive_sentiment_count integer default 0,
    negative_sentiment_count integer default 0,
    neutral_sentiment_count integer default 0,
    last_updated timestamptz default now(),
    unique(agent_id, year, month)
);

create index if not exists idx_call_analysis_calls_agent_date on call_analysis.calls (agent_id, call_date);
create index if not exists idx_call_analysis_qa_scores_call on call_analysis.qa_scores (call_id);
create index if not exists idx_call_analysis_keywords_call on call_analysis.keywords (call_id);
create index if not exists idx_call_analysis_monthly_summaries_agent on call_analysis.monthly_summaries (agent_id, year, month);
